# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own contain

jobs:
  deploy:
    docker:
      - image: cimg/base
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site
orbs:
  hugo: circleci/hugo@0.2
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: src/
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
